### NumPy - Linear Algebra Lib. for Python

## NumPy Arrays:

In [1]:
mlist = [0,1,2,3,4]

In [2]:
import numpy as np

In [3]:
# casting a list into numpy array
arr = np.array(mlist)
arr

array([0, 1, 2, 3, 4])

In [5]:
# casting a list into numpy array with specific data type to make it more efficient
myarr = np.array(mlist,np.int8)
myarr

array([0, 1, 2, 3, 4], dtype=int8)

In [10]:
# while giving specific data type if value exceeds then it will give error
np.array([1,2,829324324, 4, 5], np.int8)

OverflowError: Python integer 829324324 out of bounds for int8

In [11]:
my_matrix = [[1,2,3], [4,5,6], [7,8,9]]

# casting 2-D list into 2-D array
np.array(my_matrix)

array([[1, 2, 3],
       [4, 5, 6],
       [7, 8, 9]])

# Common ways to create numpy array

### 1. Creating array of specific range


In [15]:
# np.arange(start, end, step-size=1)
np.arange(0,10, step=2)

array([0, 2, 4, 6, 8])

In [14]:
np.arange(0,10)

array([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])

### 2. Creating arrays of all zeros

In [17]:
# np.zeros(size)
np.zeros(3)

array([0., 0., 0.])

In [18]:
# n- D array of all zeros - np.zeros(n-sized_tuple)
np.zeros((3,5))

array([[0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0.]])


### 3. Creating array of ones

In [21]:
# np.ones(size)
np.ones(5)

array([1., 1., 1., 1., 1.])

In [22]:
# n-D array of ones
np.ones((2,3))

array([[1., 1., 1.],
       [1., 1., 1.]])

### 4. Creating linearly-spaced arrays in given range

In [27]:
# linspace(start, stop, even_space = 50)
# even_space - the size of array (also generate the array from start-stop range only)
np.linspace(0,10,8)

array([ 0.        ,  1.42857143,  2.85714286,  4.28571429,  5.71428571,
        7.14285714,  8.57142857, 10.        ])

###  5. IDENTITY MATRIX using numpy (size - n*n)

In [28]:
# np.eye(size)
np.eye(3)

array([[1., 0., 0.],
       [0., 1., 0.],
       [0., 0., 1.]])

In [29]:
# np.identity(size)
np.identity(4)

array([[1., 0., 0., 0.],
       [0., 1., 0., 0.],
       [0., 0., 1., 0.],
       [0., 0., 0., 1.]])

### 6. Arrays of random numbers

In [35]:
# 1. rand - gives random numbers in uniform distribution (range: 0-1)
print(np.random.rand(2)) # 1D array
print(np.random.rand(3,5)) # 2D array
# for 2-D > np.random.rand(3,5)

[0.49769568 0.59139787]
[[0.48661917 0.94868727 0.22651296 0.64978574 0.86361175]
 [0.48416919 0.84968485 0.71495062 0.54478459 0.84725808]
 [0.22331466 0.1806735  0.4582409  0.09945402 0.07570253]]


In [38]:
# 2. randn - gives random numbers in standard normal distribution
# np.random.randn(3)
np.random.randn(3,5)

array([[ 0.56561243,  0.57183738, -1.25525302, -0.36457518, -0.15811641],
       [ 0.61236128, -0.04911079, -0.46899112,  0.51916125, -1.53367876],
       [-1.42555584, -0.47987003,  0.02562803, -1.70692396,  1.68553335]])

In [52]:
# 3. randint - np.random.randint(low_inclusive, high_exclusive, size=1 (element))
np.random.randint(0,100)

39

In [41]:
np.random.randint(0,100,20)

array([23, 90, 39, 71, 90, 69, 81, 62, 57,  6, 75, 50, 81, 73, 17, 39, 93,
       62, 57, 50], dtype=int32)

### 7. Creating Empty Array

In [50]:
temparr = np.ones((2,3))
temparr.size

6

In [48]:
# creates empty array
# In array it assigns memory block, for creating array we need to assisgn memory, in empty array we put any value
emparr = np.empty((2,2))
emparr

array([[1., 1.],
       [1., 1.]])

In [51]:
# creates empty array of specific sized predefined array (empty_size)
# replicates the size of existing array

emp_like = np.empty_like(temparr)
emp_like

array([[1., 1., 1.],
       [1., 1., 1.]])