In [1]:
import numpy as np

In [6]:
arr1 = np.arange(0,25)
arr2 = np.random.randint(0,50,27)
print(arr1)
print(arr2)

[ 0  1  2  3  4  5  6  7  8  9 10 11 12 13 14 15 16 17 18 19 20 21 22 23
 24]
[ 8  0  4 38 30 35  8 47 30 31  5 48 25 19  2  0 35 23 40 41 28 42 46 45
 22 31 31]


### 1. Reshaping array (i.e. 1-D to n-D) (Method):
syntax: `arrayName.reshape(n - rows, m - columns, ...)` and `arrayName.ravel()` - n-D array to 1-D array

In [12]:
arr_2d = arr1.reshape(5,5)
arr_2d
 
# here, multiplication of arguments in reshape() should be always 
#       equal to the size of 1-D array (base_array) & vice-versa
# error arises when above conditions are not followed

array([[ 0,  1,  2,  3,  4],
       [ 5,  6,  7,  8,  9],
       [10, 11, 12, 13, 14],
       [15, 16, 17, 18, 19],
       [20, 21, 22, 23, 24]])

In [13]:
# 1-D to 3-D
arr2.reshape(3,3,3)

array([[[ 8,  0,  4],
        [38, 30, 35],
        [ 8, 47, 30]],

       [[31,  5, 48],
        [25, 19,  2],
        [ 0, 35, 23]],

       [[40, 41, 28],
        [42, 46, 45],
        [22, 31, 31]]], dtype=int32)

In [14]:
# 2-D to 1-D  -> n*m (2-D size) = N (1-D size)
arr_2d.reshape(25)

array([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14, 15, 16,
       17, 18, 19, 20, 21, 22, 23, 24])

In [16]:
newarr = np.copy(arr_2d)
newarr

array([[ 0,  1,  2,  3,  4],
       [ 5,  6,  7,  8,  9],
       [10, 11, 12, 13, 14],
       [15, 16, 17, 18, 19],
       [20, 21, 22, 23, 24]])

In [17]:
# from n-D array to 1-D array using ravel() function
newarr_1d = newarr.ravel()
newarr_1d

array([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14, 15, 16,
       17, 18, 19, 20, 21, 22, 23, 24])

### 2. Finding Max and Min value in array (Method):
`.min() / .max()`

In [18]:
arr1.min()

np.int64(0)

In [19]:
arr1.max()

np.int64(24)

### 3. Finding INDEX of max and min value in array (Method):
`.argmin() / .argmax()`


In [20]:
arr1.argmin()

np.int64(0)

In [21]:
arr1.argmax()

np.int64(24)

### 4. Sorting an array

`.argsort()` function gives the order in which a given array must be arranged for ascending order, it returns the index number of elements present in an array

In [22]:
one = np.array([1,2,324,56,6])
one

array([  1,   2, 324,  56,   6])

In [24]:
# gives indices of the given array to be sorted
one.argsort()

array([0, 1, 4, 3, 2])

In [25]:
# using argsort() in 2-D arrays using axis

In [26]:
two = np.array([[1,2,3], [4,5,6], [7,8,0]])
two

array([[1, 2, 3],
       [4, 5, 6],
       [7, 8, 0]])

In [27]:
two.max(axis=0)

array([7, 8, 6])

In [28]:
two.argmax(axis=0)

array([2, 2, 1])

In [29]:
two.argmax(axis=1)

array([2, 2, 1])

In [30]:
two.argsort(axis=0)

array([[0, 0, 2],
       [1, 1, 0],
       [2, 2, 1]])

### 5. Finding SHAPE of array/vector (Attribute):
`arrayName.shape` - returns tuple

In [31]:
arr1.shape

(25,)

In [32]:
arr_2d.shape

(5, 5)

In [33]:
arr2.reshape(3,3,3).shape

(3, 3, 3)

### 6. Finding DATA TYPE (Attribute):
`arrayName.dtype`

In [34]:
arr1.dtype

dtype('int64')

In [35]:
np.array([1,2,2.0,0.0,12.1023243]).dtype

dtype('float64')

In [36]:
np.array(['hii', 12, 9.8, 1]).dtype

dtype('<U32')