In [1]:
import numpy as np

In [2]:
arr = np.arange(0,10)
arr

array([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])

#### Indexing is somewhat similar to python list

In [3]:
arr[8]

np.int64(8)

### slice notation can also be used in arrays same as list
`arrayName[start: stop: setps]`

In [4]:
arr[3:7]

array([3, 4, 5, 6])

In [5]:
arr[3:9:2]

array([3, 5, 7])

In [6]:
arr[:5]

array([0, 1, 2, 3, 4])

### NumPy array can Broadcast while list cannot
`arrName[start: stop: steps] = value`

In [15]:
arr[0:5] = 100

In [8]:
arr

array([100, 100, 100, 100, 100,   5,   6,   7,   8,   9])

In [10]:
arr = np.arange(0,11)    # resetting an array
arr

array([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10])

In [13]:
slice_of_arr = arr[0: int(len(arr) / 2)]
slice_of_arr

array([0, 1, 2, 3, 4])

#### NOTE: Changing an element of child array can result into changing of parent array also

- This happens because the data is not copied but is reused, NumPy does that in order to avoid memory issues of very large arrays.

In [16]:
slice_of_arr[:] = 100
slice_of_arr

array([100, 100, 100, 100, 100])

In [17]:
arr

array([100, 100, 100, 100, 100,   5,   6,   7,   8,   9,  10])

#### In order to copy an array copy() function is used

In [18]:
arr_copy = arr.copy()
arr_copy

array([100, 100, 100, 100, 100,   5,   6,   7,   8,   9,  10])

In [19]:
# changing arr_copy won't change arr because it created a copy
arr_copy[:] = 1000
arr_copy

array([1000, 1000, 1000, 1000, 1000, 1000, 1000, 1000, 1000, 1000, 1000])

In [20]:
arr

array([100, 100, 100, 100, 100,   5,   6,   7,   8,   9,  10])