##  Conditional Selection Method

In [2]:
import numpy as np

In [3]:
arr = np.arange(1,11)
arr

array([ 1,  2,  3,  4,  5,  6,  7,  8,  9, 10])

In [8]:
# To get array of boolean value
bool_arr = arr > 5
bool_arr
# it will check for each value like it compare 5 to each element if it wrong then will show false then true 

array([False, False, False, False, False,  True,  True,  True,  True,
        True])

Todo conditional selection 

That Boolean array can be used to select elements from the original array conditinally

In [9]:
arr[bool_arr]

array([ 6,  7,  8,  9, 10])

In [10]:
# Most Important
arr[arr<5]

array([1, 2, 3, 4])

In [12]:
arr1 = np.arange(11,20)
arr1

array([11, 12, 13, 14, 15, 16, 17, 18, 19])

In [13]:
arr1[arr1>12]

array([13, 14, 15, 16, 17, 18, 19])

#### finding an element in an array
`np.where(args/conditions)`

In [15]:
arr_2d = np.arange(9).reshape(3,3)
arr_2d

array([[0, 1, 2],
       [3, 4, 5],
       [6, 7, 8]])

In [16]:
np.where(arr_2d==5)

(array([1]), array([2]))

In [17]:
type(np.where(arr_2d==6))

tuple

In [18]:
np.where(arr_2d > 5)

(array([2, 2, 2]), array([0, 1, 2]))