## Indexing a Matrix (2-D Array):

In [40]:
import numpy as np

In [41]:
arr_2d = np.array([[1,2,3], [4,5,6], [7,8,9]])
arr_2d

array([[1, 2, 3],
       [4, 5, 6],
       [7, 8, 9]])

### Two formats of Grabbing Value from Matrix:

##### 1. Double Bracket Format

In [42]:
arr_2d[0]

array([1, 2, 3])

In [43]:
arr_2d[1][2]

np.int64(6)

##### 2. Single Bracket Format : (recommended)

In [44]:
arr_2d[2,1]

np.int64(8)

### Colon(:) can be use to slice certain portion of the matrices

In [45]:
arr_2d

array([[1, 2, 3],
       [4, 5, 6],
       [7, 8, 9]])

In [49]:
list(arr_2d)

[array([1, 2, 3]), array([4, 5, 6]), array([7, 8, 9])]

In [48]:
arr_2d[:, :1]    

array([[1],
       [4],
       [7]])

In [47]:
arr_2d[:, 2:]

array([[3],
       [6],
       [9]])

In [50]:
# Grabbing top right (2*2) Matrix
arr_2d[:2,1:]

array([[2, 3],
       [5, 6]])

In [52]:
arr_2d = np.arange(50).reshape(5,10)
arr_2d

array([[ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9],
       [10, 11, 12, 13, 14, 15, 16, 17, 18, 19],
       [20, 21, 22, 23, 24, 25, 26, 27, 28, 29],
       [30, 31, 32, 33, 34, 35, 36, 37, 38, 39],
       [40, 41, 42, 43, 44, 45, 46, 47, 48, 49]])

In [55]:
arr_2d[2:4, 6:8]

array([[26, 27],
       [36, 37]])

In [56]:
arr_2d[1:, :2]

array([[10, 11],
       [20, 21],
       [30, 31],
       [40, 41]])