## NumPy Operations
(same as matrix operations)

- Array with Array
- Array with Scalars
- Universal Array Functions

In [2]:
import numpy as np

In [3]:
arr = np.arange(0,11)
arr

array([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10])

#### 1. Array with array operations

NOTE: Two arrays of same SIZE and same DIMEENSIONS should be used always for performing an operations

In [4]:
arr + arr

array([ 0,  2,  4,  6,  8, 10, 12, 14, 16, 18, 20])

In [6]:
arr * arr
# ....... etc all operations

array([  0,   1,   4,   9,  16,  25,  36,  49,  64,  81, 100])

#### 2. Array with Scalars Operations

In [7]:
arr + 100

array([100, 101, 102, 103, 104, 105, 106, 107, 108, 109, 110])

In [8]:
arr - 100

array([-100,  -99,  -98,  -97,  -96,  -95,  -94,  -93,  -92,  -91,  -90])

In [9]:
arr ** 2

array([  0,   1,   4,   9,  16,  25,  36,  49,  64,  81, 100])

In [10]:
# IMP - Normal one gives ERROR
1/0

ZeroDivisionError: division by zero

In [12]:
# NumPy only gives WARNING
# first element -> 0/0, O/P -> nan
arr / arr

C:\Users\rosha\AppData\Local\Temp\ipykernel_2684\3646263853.py:3: RuntimeWarning: invalid value encountered in divide
  arr / arr


array([nan,  1.,  1.,  1.,  1.,  1.,  1.,  1.,  1.,  1.,  1.])

In [13]:
# first element -> 1/0, O/P -> inf
1/ arr

C:\Users\rosha\AppData\Local\Temp\ipykernel_2684\2861371043.py:2: RuntimeWarning: divide by zero encountered in divide
  1/ arr


array([       inf, 1.        , 0.5       , 0.33333333, 0.25      ,
       0.2       , 0.16666667, 0.14285714, 0.125     , 0.11111111,
       0.1       ])

#### 2. Universal array functions

In [14]:
# 1. Square root of every elements
np.sqrt(arr)

array([0.        , 1.        , 1.41421356, 1.73205081, 2.        ,
       2.23606798, 2.44948974, 2.64575131, 2.82842712, 3.        ,
       3.16227766])

In [15]:
# 2. Calculating Exponential of every elements
np.exp(arr)

array([1.00000000e+00, 2.71828183e+00, 7.38905610e+00, 2.00855369e+01,
       5.45981500e+01, 1.48413159e+02, 4.03428793e+02, 1.09663316e+03,
       2.98095799e+03, 8.10308393e+03, 2.20264658e+04])

In [17]:

# 3. Finding maximum/minimum element
np.max(arr)
# np.min(arr)
    # OR
arr.max()
# arr.min()


np.int64(10)

In [18]:
# 4. Performing Trignometric OPerations on every element
np.sin(arr)
np.cos(arr)
# .......etc

array([ 1.        ,  0.54030231, -0.41614684, -0.9899925 , -0.65364362,
        0.28366219,  0.96017029,  0.75390225, -0.14550003, -0.91113026,
       -0.83907153])

In [19]:
# 5. Performing LOGARITHMATIC Operations on every element
np.log(arr)

C:\Users\rosha\AppData\Local\Temp\ipykernel_2684\3553873897.py:2: RuntimeWarning: divide by zero encountered in log
  np.log(arr)


array([      -inf, 0.        , 0.69314718, 1.09861229, 1.38629436,
       1.60943791, 1.79175947, 1.94591015, 2.07944154, 2.19722458,
       2.30258509])

In [20]:
# 5. Finding sum of every elemets
np.sum(arr)
# OR
arr.sum()

np.int64(55)

In [22]:
# 6. Finding standard deviation
np.std(arr)
# OR
arr.std()


np.float64(3.1622776601683795)

In [23]:
arr_2d = np.arange(1,26).reshape(5,5)
arr_2d

array([[ 1,  2,  3,  4,  5],
       [ 6,  7,  8,  9, 10],
       [11, 12, 13, 14, 15],
       [16, 17, 18, 19, 20],
       [21, 22, 23, 24, 25]])

In [25]:
# Getting the sum of all the columns in arr_2d

# here axis = 0 means all the columns
# axis = 1 means all the rows

np.sum(arr_2d, axis=0)
#  OR
np.sum(arr_2d, axis=1)

array([ 15,  40,  65,  90, 115])

##### There are many more universal functions

In [49]:
arr_2d = np.arange(0,10).reshape(5,2)
arr_2d

array([[0, 1],
       [2, 3],
       [4, 5],
       [6, 7],
       [8, 9]])

In [50]:
arr_2d.sum(axis=0)

array([20, 25])

In [29]:
arr_3d = np.arange(27).reshape(3, 3, 3)
arr_3d

array([[[ 0,  1,  2],
        [ 3,  4,  5],
        [ 6,  7,  8]],

       [[ 9, 10, 11],
        [12, 13, 14],
        [15, 16, 17]],

       [[18, 19, 20],
        [21, 22, 23],
        [24, 25, 26]]])

In [30]:
list(arr_3d)

[array([[0, 1, 2],
        [3, 4, 5],
        [6, 7, 8]]),
 array([[ 9, 10, 11],
        [12, 13, 14],
        [15, 16, 17]]),
 array([[18, 19, 20],
        [21, 22, 23],
        [24, 25, 26]])]

axis=0 means column wise

axis=1 means row wise

axis=2 means take whole array together (in axis=0,1 it will take one element from different array)

[0, 1, 2], [3, 4, 5],[6, 7, 8]
[ 9, 10, 11], [12, 13, 14], [15, 16, 17]
[18, 19, 20],  [21, 22, 23], [24, 25, 26]
now think how it works

In [48]:
arr_3d.sum(axis=2)

array([[ 3, 12, 21],
       [30, 39, 48],
       [57, 66, 75]])

# Many more [Universal Array Functions 😁](https://numpy.org/doc/stable/reference/ufuncs.html)