## Few More Important Methods in NumPy

In [2]:
import numpy as np

In [3]:
arr = np.arange(9)
arr

array([0, 1, 2, 3, 4, 5, 6, 7, 8])

In [5]:
arr_2d = arr.reshape(3,3)
arr_2d

array([[0, 1, 2],
       [3, 4, 5],
       [6, 7, 8]])

In [6]:
arr_1x9 = arr.reshape(1,9)
arr_1x9

array([[0, 1, 2, 3, 4, 5, 6, 7, 8]])

### 1. Trasnpose of a Matrix

In [8]:
arr_2d.T

array([[0, 3, 6],
       [1, 4, 7],
       [2, 5, 8]])

In [9]:
arr_1x9.T

array([[0],
       [1],
       [2],
       [3],
       [4],
       [5],
       [6],
       [7],
       [8]])

In [10]:
arr.T

array([0, 1, 2, 3, 4, 5, 6, 7, 8])

### 2. Fetching iterator using .flat attribute

In [11]:
arr.flat

In [12]:
for item in arr.flat:
    print(item)

0
1
2
3
4
5
6
7
8


### 3. Finding number of dimensions using ndim

In [13]:
arr.ndim

1

In [14]:

arr_2d.ndim

2

### 4. Finding the bytes of array

In [15]:
arr.nbytes

72

In [16]:
np.arange(0,15).nbytes

120

In [24]:
np.random.rand(1)

array([0.335436])

In [17]:
np.random.rand(1).nbytes

8

In [20]:
new = np.random.randint(1,6,1)
new

array([1], dtype=int32)

In [22]:
new.nbytes

4

### 5. Finding number of non-zero elements

In [25]:
nonZeroArr = np.array([0,1,2,0,4,0,5,6,7])
nonZeroArr_2d = nonZeroArr.reshape(3,3)
nonZeroArr.size

9

In [27]:
#  counts the number of non-zeros
np.count_nonzero(nonZeroArr)

6

In [28]:
# gives the tuple representing dimensions that have non-zeros
np.nonzero(nonZeroArr)

(array([1, 2, 4, 6, 7, 8]),)

In [29]:
# Gives the tuple representing dimensions that have non-zeros
print(nonZeroArr_2d)
np.nonzero(nonZeroArr_2d)

[[0 1 2]
 [0 4 0]
 [5 6 7]]


(array([0, 0, 1, 2, 2, 2]), array([1, 2, 1, 0, 1, 2]))

### 6. NumPy Array to list
`.tolist()`

In [30]:
arr

array([0, 1, 2, 3, 4, 5, 6, 7, 8])

In [31]:
arr.tolist()

[0, 1, 2, 3, 4, 5, 6, 7, 8]

# Many more [Attributes and Methods](https://numpy.org/doc/stable/reference/generated/numpy.ndarray.html) 😁